# this file is used to build production containers on remote host.

version: '2'

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
  redis:
    restart: always
    image: redis:3.0
    expose:
      - "6379"
  elasticsearch:
    image: elasticsearch:2.3
    restart: always
    expose:
      - "9200"
  app:
    environment:
      DJANGO_SECRET_KEY: changeme
      DATABASE_URL: postgres://app_user:changeme@db/app_db
      CACHE_URL: redis://redis
      ELASTICSEARCH_ENDPOINT: elasticsearch
    build:
      context: .
      dockerfile: dockerfiles/docker_django_prod.conf
    volumes:
      - static-root:/code/bakerydemo/collect_static
      - media-root:/code/bakerydemo/media
    links:
      - db:db
      - redis:redis
      - elasticsearch:elasticsearch
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
      - elasticsearch


  nginx:
    restart: always
    volumes:
      - media-root:/code/bakerydemo/media
      - static-root:/code/bakerydemo/static
    build:
     context: .
     dockerfile: dockerfiles/docker_nginx.conf
    depends_on:
     - app
    labels:
      - "traefik.enable=true"
      # we have only 5 attempts per week for requesting/updating certificates
      # be carefull with that.
      - "traefik.http.routers.nginx.rule=Host(`www.pythonx.ru`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"

  traefik:
    image: "traefik:v2.0.1"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging$
      - "--certificatesresolvers.myresolver.acme.email=qb89@yandex.ru"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  media-root:
  static-root:
